AdventureClub/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name="club"

urlpatterns = [
    # path('', views.home),
    path('', views.index, name='index'),

    # urls for user login/register/logout
    path('register/', views.RegisterClub, name='register'),
    path('signUp/', views.signup, name='signUp'),
    path('signOut/', views.signOut, name='signOut'),
    path('signIn/', views.signIn, name='signIn'),
    path('createEvent/',views.createEvent,name="createEvent"),
    path('myClubs/',views.myClubs,name="myClubs"),
    path('onGoingEvents/',views.onGoingEvents,name="events"),
    path('searchResults/',views.searchResults,name="searchResults"),
    path('detail/<int:pk>/',views.clubDetail,name="detail"),
    path('deleteClub/<int:pk>/',views.deleteClub.as_view(),name='deleteClub'),
    path('updateClub/<int:pk>/',views.updateClub.as_view(),name='updateClub'),
    path('popEvent/<int:pk>/',views.popedEvent,name='popEvent'),
    path('eventDetails/<int:pk>/',views.eventDetails.as_view(),name='eventDetails'),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sayahat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('locapp.urls')),
    path('/', include('AdventureClub.urls')),
    path('SayahatAdventure/', include('AdventureClub.urls')),
    path('accounts/', include('allauth.urls')),
    #for configuring media files on heroku
#     re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve,
        kwargs=dict(document_root=settings.MEDIA_ROOT)),
    
    # urls for password reset at adventure club side
    # 1. for entering email to reset password
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='AdventureClubs/password_reset.html',
                                                                 email_template_name='AdventureClubs/myTemp.html'),
         name='password_reset'),

    # 2. for sending email to user who want to change password
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='AdventureClubs/password_reset_sent.html'),
         name='password_reset_done'),
    # urls for password reset
    # 3. The link from email on which user clicks to reset password
    path('lol/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='AdventureClubs/password_reset_fill.html'),
         name='password_reset_confirm'),
    # 4. on successful reset of password
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='AdventureClubs/password_reset_complete.html'),
         name='password_reset_complete'),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locapp/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

# from django.contrib.auth.decorators import login_required
app_name = 'locapp'

urlpatterns = [

    # path('', views.soclogin),
    path('', views.DestinationView, name='dest'),
    # path('tourist/', views.TouristView, name='tourist'),
    path('<int:pk>/', views.dest_view2, name="show_dest"),
    path('logout/', views.logoutuser, name='logout'),
    path('loc_meta_detail/<int:pk>', views.loc_meta_view, name="loc_meta_detail"),
    #     path('addDestination/',views.userDestForm.as_view(),name='addLoc'),
    #     path('addCity/',views.userCityForm.as_view(),name='addCity'),
    path('addCity/', views.usercityform, name='addCity'),
    #     path('addPlace/',views.userPlaceForm.as_view(),name='addPlace'),
    path('addPlace/', views.userplaceform, name='addPlace'),
    path('aboutUs/',views.aboutUs,name='aboutUs'),
    path('addRating/', views.direct_rating, name='addRating'),
    path('blog/<int:key>/',views.Blog,name='Blog'),

    path('searchsuggestion/', views.search, name='search'),

]

AdventureClub/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class AdventureClub(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    club_name = models.CharField(max_length=50)
    contact = models.CharField(max_length=11, default='')
    email = models.EmailField(null=True)
    featured = models.BooleanField(default=False)
    club_image = models.ImageField(upload_to='AdventureClub/Club_Images', null=True)
    club_address = models.CharField(max_length=80)
    city = models.CharField(null=False, blank=False, default="", max_length=25)

    def __str__(self):
        return self.club_name


class AdventureEvent(models.Model):
    event_by = models.ForeignKey(AdventureClub, on_delete=models.CASCADE,default="")
    # event_by = models.CharField(max_length=50)
    title = models.CharField(max_length=80)
    overview = models.CharField(max_length=120, default='')
    image = models.ImageField(null=True, upload_to='AdventureClub/AdventureEventPics')
    featured = models.BooleanField(default=False)
    event_start_date = models.DateField()
    event_end_date = models.DateField()
    start_point = models.CharField(max_length=70, null=True,default="")
    destination = models.CharField(max_length=70, null=True,default="")

    def __str__(self):
        return "Event- " + self.title

# class EventDetails(models.Model):

#     booked_event = models.ForeignKey(AdventureEvent, on_delete=models.CASCADE)
#     start_point = models.CharField(max_length=70, null=True)
#     destination = models.CharField(max_length=70, null=True)

#     def __str__(self):
#         return "BookedEventFrom- " + str(self.booked_event)


# class TouristReview(models.Model):
#     tourist_id = models.ForeignKey(User, on_delete=models.CASCADE, )
#     adventureevent = models.ForeignKey(AdventureEvent, on_delete=models.CASCADE)
#     tourist_review = models.CharField(max_length=256)

#     def __str__(self):
#         return str(self.tourist_id)

AdventureClub/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import AdventureClub, AdventureEvent


class clubRegisterationForm(forms.ModelForm):
    owner = forms.CharField.widget(attrs={'readonly': 'true'})

    class Meta:
        model = AdventureClub
        fields = '__all__'
        exclude = ('owner', 'featured',)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class DateInput(forms.DateInput):
    input_type = 'date'


class adventureEventform(forms.ModelForm):
    class Meta:
        model = AdventureEvent
        exclude = ('event_by','featured',)
        fields = '__all__'
        widgets = {
            'event_start_date': DateInput(),
            'event_end_date': DateInput(),
        }

AdventureClub/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.urls import reverse_lazy
from datetime import date
from django.views.generic import DetailView
from . import models
from .forms import clubRegisterationForm, SignUpForm, adventureEventform
from django.views.generic.edit import DeleteView, UpdateView, CreateView


# Create your views here.

def index(request):
    cities = models.AdventureClub.objects.values('city')
    clubs = ''
    featuredClubs = models.AdventureClub.objects.filter(featured=True)
    featuredEvents = models.AdventureEvent.objects.filter(featured=True)
    deleteEvent()
    if request.method == 'POST':
        query = request.POST.get('city')
        clubs = models.AdventureClub.objects.filter(city=query)
    sliderList = [1, 2, 3]
    context = {'user': request.user, 'city': cities, 'club': clubs, 'FC': featuredClubs, 'FE': featuredEvents,
               'sl': sliderList}
    return render(request, 'AdventureClubs/index.html', context)


def popedEvent(request, pk):
    poppedEvent = models.AdventureEvent.objects.filter(id=pk)
    context = {'pop': poppedEvent}
    return render(request, 'AdventureClubs/index.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        users_email = models.User.objects.all()
        if form.is_valid():
            for mail in users_email:
                if form.cleaned_data['email'] == mail.email:
                    # print("emails = ", mail.email)
                    messages.info(request, 'Use a different email, the email is already in use!')
                    return redirect('club:signUp')
            form.save()
            messages.info(request, "You are registered successfully!")
            return redirect('club:signIn')
    else:
        form = SignUpForm()
    context = {'form': form}
    return render(request, 'AdventureClubs/signUp.html', context)


def signIn(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user, backend=None)
                    messages.info(request, f"You are now logged in as {username}")
                    # return HttpResponseRedirect('/club/')
                    return redirect('club:index')
            else:
                form = AuthenticationForm()
                msg = "Incorrect username or password!"
                return render(request, 'AdventureClubs/SignIn.html', context={'msg': msg, 'form': form})
                # return redirect('club:signIn')
        else:
            form = AuthenticationForm()
            return render(request, 'AdventureClubs/SignIn.html', context={'form': form})
    else:
        return HttpResponseRedirect('/club/index/')


def signOut(request):
    logout(request)
    return redirect('club:signIn')


def RegisterClub(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = clubRegisterationForm(request.POST, request.FILES)
            if form.is_valid():
                form = form.save(commit=False)
                form.owner = request.user
                form.save()
                messages.success(request, 'Your adventure club is registered successfully!')
                return redirect('club:myClubs')
        form = clubRegisterationForm()
        return render(request, 'AdventureClubs/registerClub.html', context={'form': form, })
    else:
        return redirect('club:signIn')


def createEvent(request):
    if request.user.is_authenticated:
        clubs = models.AdventureClub.objects.filter(owner=request.user)
        if request.method == 'POST':
            form = adventureEventform(request.POST, request.FILES)
            print(form.errors)
            if form.is_valid():
                club = request.POST.get('club')
                # club_rec = models.AdventureClub.objects.filter(club_name=club).values(models.AdventureClub.pk)
                # club_rec = models.AdventureClub.objects.get(club_name=club)
                # print("Club Id", club_rec.pk)
                # form = form.save(commit=False)
                # form.event_by = club_rec.pk
                # form.save()
                # ev_by = club
                # club_ref = models.AdventureClub.objects.get(id=models.AdventureClub.objects.filter(club_name=club))
                # print(club_ref)
                # models.AdventureEvent.event_by = club_rec.pk
                title = form.cleaned_data['title']
                overview = form.cleaned_data['overview']
                image = form.cleaned_data['image']
                event_start_date = form.cleaned_data['event_start_date']
                event_end_date = form.cleaned_data['event_end_date']
                startpoint = form.cleaned_data['start_point']
                destinationpoint = form.cleaned_data['destination']
                eventmodelobj = models.AdventureEvent(event_by=models.AdventureClub.objects.get(club_name=club), title=title
                                                    , overview=overview, image=image
                                                    , event_start_date=event_start_date, event_end_date=event_end_date, start_point=startpoint, destination=destinationpoint)
                eventmodelobj.save()
                messages.success(request, 'Event is created successfully!')
                return redirect('club:events')
        form = adventureEventform()
        return render(request, 'AdventureClubs/adventureevent_form.html', context={'form': form, 'clubs': clubs, })
    else:
        return redirect('club:signIn')


def home(request):
    return render(request, 'AdventureClubs/home.html')


def myClubs(request):
    if request.user.is_authenticated:
        userClub = models.AdventureClub.objects.filter(owner=request.user)
        return render(request, "AdventureClubs/myClubs.html", context={'clubs': userClub})
    else:
        return redirect('club:signIn')


def onGoingEvents(request):
    events = models.AdventureEvent.objects.all()
    return render(request, "AdventureClubs/events.html", context={'event': events})


def searchResults(request):
    queryset = models.AdventureEvent.objects.all()
    query = request.GET.get('city')
    # print("--------------------------------------------", query)
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(overview__icontains=query)

        ).distinct()

    context = {
        'FE': queryset
    }
    return render(request, 'AdventureClubs/search_results.html', context)


def clubDetail(request, pk):
    if request.user.is_authenticated:
        obj = models.AdventureClub.objects.filter(id=pk)
        obj1 = models.AdventureEvent.objects.filter(event_by=pk)
        context = {'fc': obj, 'fe': obj1}
        return render(request, 'AdventureClubs/clubDetail.html', context)
    else:
        return redirect('club:signIn')


class deleteClub(DeleteView):
    model = models.AdventureClub
    success_url = reverse_lazy('club:myClubs')
    template_name = 'AdventureClubs/adventureclub_confirm_delete.html'


class updateClub(UpdateView):
    model = models.AdventureClub
    fields = ('club_name', 'contact', 'email', 'club_image', 'club_address', 'city')
    success_url = reverse_lazy('club:myClubs')
    template_name = 'AdventureClubs/registerClub.html'


# def myEvents(request):
#     userEvents = models.AdventureEvent.objects.filter()
#     return render(request, "AdventureClubs/myEvents.html", context={'clubs': userEvents})

class eventDetails(DetailView):
    model = models.AdventureEvent
    context_object_name = 'fe'
    template_name = 'AdventureClubs/eventDetails.html'

def deleteEvent():
    expiredEvent = models.AdventureEvent.objects.all()

    for e in expiredEvent:
        if date.today() >= e.event_end_date:
            e.delete()

AdventureClub/templates/AdventureClubs/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sayahat</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <!-- new -->

  
        <!-- Font Awesome -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
        />
        <!-- Google Fonts Poppins & Satsfy-->
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
        
    
        <!-- Bootstrap core css -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <!-- MDB -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css"
        rel="stylesheet"
        />
        <!-- Swiper css -->
        <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    
        <!-- custom css -->
        <link rel="stylesheet" href="{% static 'styles/style2.css' %}">
        


    <!-- old -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css'%}"
    />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'styles/main_styles.css'%}"
    />
    

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
     <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- satisfy font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <!-- <link rel="stylesheet" href="css/fontawesome.min.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <!-- Styles -->
    <link rel="stylesheet" href="{%static 'styles/style.css'%}">

    <!-- swiper cdn -->

    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />



     <!-- animation on scroll -->
     <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
     <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

    <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 5000)
  </script>
	<style>
		#mylink{
			text-decoration:none;
		}
    
	</style>
<style>
  .hero-btn{
  display:inline-block;
  text-decoration:none;
  color:#fff;
  border: 1px solid #fff;
  padding: 12px 34px;
  font-size: 13px;
  background: transparent;
  position: relative;
  cursor:pointer;
}
.hero-btn:hover{
  border: 1px solid #e74c3c;
  background:#e74c3c;
  transition: 0.5s;
}
.red-btn{
 border: 1px solid #e74c3c;
 background: transparent;
 color:#e74c3c;

}
.red-btn:hover{
 color:#fff;
 background-color: #e74c3c;
}

</style>
</head>





<body>
  <!-- old -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'club:index'%}"><img src="{% static 'images/logo2.png'%}"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>

      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'club:index'%}">Home</a>
          </li>
            <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{%url 'locapp:dest'%}">Sayahat Solo</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{%url 'club:events'%}">On going Events</a>
          </li>

          {%if user.is_authenticated%}
          <div class="dropdown">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Manage Adventure Clubs
            </a>
          
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="nav-link" href="{%url 'club:myClubs'%}">My Clubs</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="nav-link" href="{%url 'club:register'%}">Register Club</a></li>
            <li><a class="nav-link" href="{%url 'club:createEvent'%}">Create Event</a></li>
            
          </ul>
        
        </li>
      </div>
          <li class="nav-item">
          <a class="nav-link" href="{%url 'club:signOut'%}">Logout</a>
        </li>
          {%else%}

          <li class="nav-item">
          <a class="nav-link" href="{%url 'club:signIn'%}">Sign in</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{%url 'club:signUp'%}">Sign up</a>
        </li>
      {% endif %}
            <li class="nav-item">
            <a class="nav-link" href="{%url 'locapp:aboutUs'%}">About Us</a>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto">
          <a href="#footer"> <button class="btn" >Contact Us</button> </a>
        </ul>
      </div>
    </div>
  </nav>


{% block body_block %}
{% endblock %}
{%include 'locapp/newfooter.html'%}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="{%static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
<script src="{%static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
<script src="{%static 'js/custom.js'%}"></script>
<script>
  AOS.init();
</script>
<!-- new -->
<script type="text/javacript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- bootstrap js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"
></script>

<script>
  $(document).ready(function(){
     $('.dropdown-toggle').dropdown()
 });
 </script>
</body>
</html>

AdventureClub/templates/AdventureClubs/myClubs.html
{% extends 'AdventureClubs/base.html' %}
 <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
{% block body_block %}
<div id="msg">
  {% if messages %}
  <div id="top-alert" class="alert alert-info" role="alert">
    <div class="text-center">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>{{request.user}}</strong>
      {% for message in messages %}
      <!-- <div class="alert {{ message.tags }} m-2" id="msg" role="alert"> -->
      {{ message }}
      <!-- </div> -->
      {% endfor %}
    </div>
  </div>
  {% endif %}
</div>

{% if clubs %}
<h2 class="d-flex justify-content-center text-uppercase" style="margin-top: 90px;">Welcome  <span class="text-success" style="margin-left: 10px; margin-right: 10px;"> "{{request.user}}"</span> Your Registered clubs</h2>
  <section id="featured">
    <div class="container" data-aos="fade-down">

      <div class="row px-0 py-2 mb-5 d-flex justify-content-center">
      {%for fc in clubs%}
        <div class="col-lg-3 px-2 my-3">
          <div class="card-design">
            <div class="image">
              <img src="{{fc.club_image.url}}" alt="">
            </div>
            <div class="card-text shadow">
              <div class="item">
                
                <h4 class="h4">{{fc.club_name}}</h4>
              </div>
              <div class="item mt-5 d-flex justify-content-around">
                    <a class="btn btn-outline-danger" href="{%url 'club:deleteClub' pk=fc.id %}">Delete</a>
					  <a class="btn btn-outline-danger" style="margin-left: 10px;" href="{%url 'club:updateClub' pk=fc.id %}">Edit</a>
              </div>

            </div>
          </div>
        </div>

          {%empty%}
        
        {%endfor%}
      </div>
    </div>
  </section>
  {% else %}
  <div class="myJumbotron container-fluid bg-white shadow d-flex  justify-content-center">
  <h3 class="d-flex justify-content-center">You don't have any Registered club, <a href="{% url 'club:register' %}"> Click here to register club!</a></h3>  
  </div>
{% endif %}
{% endblock %}

AdventureClub/templates/AdventureClubs/myEvents.html
{% extends 'AdventureClubs/base.html' %}

{% block body_block %}
<div class="mt-5"></div>
<section class="latest-posts" style="margin-top:100px;">
		<div class="row">
				<div class="col text-center">
					<div class="section_title">
                        <h1 class="d-flex justify-content-center text-uppercase" style="margin-bottom: 50px">Welcome  <span class="text-success">" {{request.user}} "</span> Your Registered clubs</h1>
					</div>
				</div>
			</div>
      <div class="container" data-aos="fade-up">
        <div class="row d-flex justify-content-center" style="padding:20px 20px 20px 20px;">
      {%for fc in clubs%}
			<div class="col-sm-4 py-3 py-sm-0">
              <div class="card shadow">
                  <div class="inner">
                      <a href="{%url 'club:detail' pk=fc.id %}"><img src="{{fc.club_image.url}}"  class="card-img-top" href="#" alt="..."></a>
                  </div>

                  <div class="card-body text-center">
                    <h5 class="card-title">{{fc.club_name}}</h5>

					  <a class="btn btn-outline-danger" href="{%url 'club:deleteClub' pk=fc.id %}">Delete</a>
					  <a class="btn btn-outline-success" href="{%url 'club:updateClub' pk=fc.id %}">Edit</a>

                  </div>
              </div>
          </div>
{%empty%}
            <h1 class="d-flex justify-content-center">You don't have any Registered club</h1>


      {%endfor%}
        </div>
      </div>
    </section>

{% endblock %}

AdventureClub/templates/AdventureClubs/myTemp.html
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

    "Please go to the following page and choose a new password:"
    {% block reset_link %}
        {{ protocol }}://127.0.0.1:8000{% url 'password_reset_confirm' uid token %}
        uid: {{ uid }}
        token: {{ token }}
    {% endblock %}
'Your username, in case you’ve forgotten:' {{ user.get_username }}

    "Thanks for using our site!"