AdventureClub/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name="club"

urlpatterns = [
    # path('', views.home),
    path('', views.index, name='index'),

    # urls for user login/register/logout
    path('register/', views.RegisterClub, name='register'),
    path('signUp/', views.signup, name='signUp'),
    path('signOut/', views.signOut, name='signOut'),
    path('signIn/', views.signIn, name='signIn'),
    path('createEvent/',views.createEvent,name="createEvent"),
    path('myClubs/',views.myClubs,name="myClubs"),
    path('onGoingEvents/',views.onGoingEvents,name="events"),
    path('searchResults/',views.searchResults,name="searchResults"),
    path('detail/<int:pk>/',views.clubDetail,name="detail"),
    path('deleteClub/<int:pk>/',views.deleteClub.as_view(),name='deleteClub'),
    path('updateClub/<int:pk>/',views.updateClub.as_view(),name='updateClub'),
    path('popEvent/<int:pk>/',views.popedEvent,name='popEvent'),
    path('eventDetails/<int:pk>/',views.eventDetails.as_view(),name='eventDetails'),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sayahat/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('locapp.urls')),
    path('/', include('AdventureClub.urls')),
    path('SayahatAdventure/', include('AdventureClub.urls')),
    path('accounts/', include('allauth.urls')),
    #for configuring media files on heroku
#     re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve,
        kwargs=dict(document_root=settings.MEDIA_ROOT)),
    
    # urls for password reset at adventure club side
    # 1. for entering email to reset password
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='AdventureClubs/password_reset.html',
                                                                 email_template_name='AdventureClubs/myTemp.html'),
         name='password_reset'),

    # 2. for sending email to user who want to change password
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='AdventureClubs/password_reset_sent.html'),
         name='password_reset_done'),
    # urls for password reset
    # 3. The link from email on which user clicks to reset password
    path('lol/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='AdventureClubs/password_reset_fill.html'),
         name='password_reset_confirm'),
    # 4. on successful reset of password
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='AdventureClubs/password_reset_complete.html'),
         name='password_reset_complete'),

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locapp/urls.py
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

# from django.contrib.auth.decorators import login_required
app_name = 'locapp'

urlpatterns = [

    # path('', views.soclogin),
    path('', views.DestinationView, name='dest'),
    # path('tourist/', views.TouristView, name='tourist'),
    path('<int:pk>/', views.dest_view2, name="show_dest"),
    path('logout/', views.logoutuser, name='logout'),
    path('loc_meta_detail/<int:pk>', views.loc_meta_view, name="loc_meta_detail"),
    #     path('addDestination/',views.userDestForm.as_view(),name='addLoc'),
    #     path('addCity/',views.userCityForm.as_view(),name='addCity'),
    path('addCity/', views.usercityform, name='addCity'),
    #     path('addPlace/',views.userPlaceForm.as_view(),name='addPlace'),
    path('addPlace/', views.userplaceform, name='addPlace'),
    path('aboutUs/',views.aboutUs,name='aboutUs'),
    path('addRating/', views.direct_rating, name='addRating'),
    path('blog/<int:key>/',views.Blog,name='Blog'),

    path('searchsuggestion/', views.search, name='search'),

]

locapp/forms.py
from django import forms
from .models import Destination, Tourist, DestinationMetaDetails, DestinationCityDetails, PlaceRatings

class DestinationForm(forms.ModelForm):
    destination=forms.CharField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter Name of City'}),label='')
    class Meta:
        model = Destination
        fields = ('destination',)

class TouristForm(forms.ModelForm):

    class Meta:
        model = Tourist
        fields = ('tourist_name','tourist_latitude','tourist_longitude','tourist_location')

class UserCityForm(forms.ModelForm):
    destination_desc= forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":10}))
    
    class Meta:
        model = DestinationCityDetails
        fields = ('destination_name','destinationImage','destination_desc')
        

class UserPlaceForm(forms.ModelForm):
    meta_destination_desc= forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":10}))
    class Meta:
        model = DestinationMetaDetails
        fields = ('meta_destination','meta_destination_name','meta_destination_Image','meta_destination_desc','destination_extras')


class PlaceRatingForm(forms.ModelForm):
    class Meta:
        model = PlaceRatings
        fields = ('place_name',)

locapp/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from django.urls import reverse_lazy, reverse
from .models import Destination, Tourist, DestinationCityDetails, DestinationMetaDetails, PlaceRatings
from locapp.forms import DestinationForm, TouristForm, UserCityForm, UserPlaceForm, PlaceRatingForm
from django.contrib.auth import logout
from .utils import location_module
from django.contrib import messages
from geopy.geocoders import Nominatim

# Create your views here.
def soclogin(request):
    return render(request, 'locapp/login.html')

def DestinationView(request):
    u_ip = request.META["REMOTE_ADDR"]
    map=''
    uname = request.user.username
    if request.method == "POST":
        fm = DestinationForm(request.POST)
        if fm.is_valid():
            fmwait = fm.save(commit=False)
            destination_ = request.POST.get('destination')
            loc_details=DestinationCityDetails.objects.filter(destination_name__icontains=destination_)
            if not loc_details.exists():
                messages.info(request, "The Location that you are Searching for has not yet been included :(")
                return redirect(reverse('locapp:dest'))
            dest_details=location_module(loc_details[0],u_ip)
            print(dest_details)

            distance=dest_details.pop(0)
            map = dest_details.pop(0)
            dest_meta_details = dest_details.pop(0)
            tourist_lat = dest_details.pop(0)
            tourist_lon = dest_details.pop(0)
            tourist_locdetails = dest_details.pop(0)
            dest_lat=dest_details.pop(0)
            dest_lon=dest_details.pop(0)
            fmwait.destination = destination_
            fmwait.distance=distance

            fmwait.save()
            touristobj = Tourist(tourist_name=uname,
            tourist_latitude= tourist_lat, tourist_longitude=tourist_lon, tourist_location = tourist_locdetails)
            touristobj.save()

            fm = DestinationForm()
            return render(request,'locapp/locationdetails.html', context={'form':fm, 'map': map,
                    'username':uname,'dest_details': loc_details, 'distance': distance, 'dest_meta_details':dest_meta_details,
                                              'tourist_lat':tourist_lat,'tourist_lon':tourist_lon,'dest_lat':dest_lat,'dest_lon':dest_lon})

    

    popular_dest=DestinationMetaDetails.objects.filter(admin_approved=True,place_rating__in=[4,5])
    fm = DestinationForm()
    obj = DestinationCityDetails.objects.filter(admin_approved=True, city_rating__in=[4,5])[0:8]
    obj1 = DestinationCityDetails.objects.filter(admin_approved=True).order_by('?')[0:8]
    all_obj=DestinationCityDetails.objects.filter(admin_approved=True)

    sl=[1,2,3]
        
    return render(request,'locapp/index.html',
                  context={'form':fm, 'map': map,'username':uname,'sl':sl,'obj':obj,'popular':popular_dest,'obj1':obj1,'allObj':all_obj})



def dest_view2(request,pk):
    u_ip = request.META["REMOTE_ADDR"]
    obj=DestinationCityDetails.objects.filter(id=pk)
    details=location_module(obj[0],u_ip)
    distance=details[0]
    mapobj=details[1]
    dest_meta_details=details[2]
    tourist_lat = details[3]
    tourist_lon = details[4]
    context={'dest_details':obj,'distance':distance,'map':mapobj,'dest_meta_details':dest_meta_details
             ,'tourist_lat':tourist_lat,'tourist_lon':tourist_lon,'dest_lat':details[6],'dest_lon':details[7]}
    return render(request,'locapp/locationdetails.html',context)


def logoutuser(request):
    logout(request)
    return redirect('/')


def loc_meta_view(request, pk):
    dest_meta_details = DestinationMetaDetails.objects.filter(id = pk)
    dest_details=location_module(dest_meta_details[0])

    if dest_details == 'not found':
        return render(request, 'locapp/meta_dest_error_details.html', context={'dest_meta_details':dest_meta_details})
    else:
        distance = dest_details.pop(0)
        map = dest_details.pop(0)
        dest_meta = dest_details.pop(0)
        tourist_lat = dest_details.pop(0)
        tourist_lon = dest_details.pop(0)
        tourist_locdetails = dest_details.pop(0)
        dest_lat = dest_details.pop(0)
        dest_lon = dest_details.pop(0)
        return render(request, 'locapp/meta_dest_map.html',
            context={'dest_meta_details': dest_meta_details,'map':map,'distance':distance,
                    'tourist_lat':tourist_lat,'tourist_lon':tourist_lon,'dest_lat':dest_lat,'dest_lon':dest_lon})



def usercityform(request):
    if request.user.is_authenticated:
        rating_count = 0
        rating_sum = 0
        citydetails = DestinationCityDetails.objects.all()
        if request.method == 'POST':
            form = UserCityForm(request.POST, request.FILES)
            cityname = request.POST.get('destination_name')
            cityname = cityname.upper()
            rating = request.POST.get('rating')
            placeratinginfo = PlaceRatings.objects.filter(user_info=request.user, place_name=cityname)
            if not placeratinginfo.exists():
                modelobj2 = PlaceRatings(
                    user_info=request.user,
                    place_name=cityname,
                    place_ratings=rating
                )
                modelobj2.save()


            # This is to calculate and save total rating
            ratedplaces = PlaceRatings.objects.all()
            for info in ratedplaces:
                if cityname.lower() == info.place_name.lower():
                    rating_count += 1
                    rating_sum += info.place_ratings

            total_rating = rating_sum / rating_count
            print(total_rating)
            # print("Total Rating: ", total_rating)
            mobj = DestinationCityDetails.objects.filter(destination_name=cityname.upper()).update(city_rating=total_rating)

            for city in citydetails:
                if cityname.upper() == city.destination_name.upper():
                    form = UserCityForm()
                    messages.warning(request,
                                    f"The city {cityname} already exist, try with other city, your ratings if for the first time, will be noted!")
                    # return reverse_lazy('club:addCity')
                    return render(request, 'locapp/userCityForm.html', context={'form': form})
            if form.is_valid():
                modelobj = DestinationCityDetails(
                    # destination_name=form.cleaned_data['destination_name'],
                    destination_name=cityname.upper(),
                    destinationImage=form.cleaned_data['destinationImage'],
                    destination_desc=form.cleaned_data['destination_desc'],
                    # destination_extras=form.cleaned_data['destination_extras'],
                    city_rating=total_rating
                )
                # form.save(commit=False)
                # form.city_rating = rating
                modelobj.save()

                messages.info(request, "Your city information has been sent for the approval!")
                # form.save()
        form = UserCityForm()
        return render(request, 'locapp/userCityForm.html', context={'form': form})
    else:
        messages.info(request,"You need to login to avail this option!")
        return redirect('locapp:dest')


def userplaceform(request):
    if request.user.is_authenticated:
        rating_count = 0
        rating_sum = 0
        place_details = DestinationMetaDetails.objects.all()
        print(request.user)
        if request.method == 'POST':
            form = UserPlaceForm(request.POST, request.FILES)
            placename = request.POST.get('meta_destination_name')
            placename = placename.upper()
            print(placename)
            rating = request.POST.get('rating')
            placeratinginfo = PlaceRatings.objects.filter(user_info=request.user, place_name=placename)
            if not placeratinginfo.exists():
                modelobj2 = PlaceRatings(
                    user_info=request.user,
                    place_name=placename,
                    place_ratings=rating
                )
                modelobj2.save()

            ratedplaces = PlaceRatings.objects.all()
            for info in ratedplaces:
                if placename.lower() == info.place_name.lower():
                    rating_count += 1
                    rating_sum += info.place_ratings
            total_rating = rating_sum / rating_count
            mobj = DestinationMetaDetails.objects.filter(meta_destination_name=placename.upper()).update(
                place_rating=total_rating)
            for place in place_details:
                if placename.upper() == place.meta_destination_name.upper():
                    form = UserPlaceForm()
                    messages.warning(request,
                                    f"The place {placename} already exist, your ratings if for the first time, will be noted!!")
                    return render(request, 'locapp/userPlaceForm.html', context={'form': form})
            if form.is_valid():
                modelobj = DestinationMetaDetails(
                    meta_destination=form.cleaned_data['meta_destination'],
                    meta_destination_name=placename.upper(),
                    meta_destination_Image=form.cleaned_data['meta_destination_Image'],
                    meta_destination_desc=form.cleaned_data['meta_destination_desc'],
                    destination_extras=form.cleaned_data['destination_extras'],
                    place_rating=total_rating
                )
                modelobj.save()

                messages.info(request, "Your city information has been sent for the approval!")
        form = UserPlaceForm()
        return render(request, 'locapp/userPlaceForm.html', context={'form': form})
    else:
        messages.info(request,"You need to login to avail this option!")

locapp/templates/locapp/base.html
<!DOCTYPE html>
{%load static%}
{% load socialaccount %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link
      rel="stylesheet"
      type="text/css"
      href="{%static 'styles/main_styles.css'%}"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>

     <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- satisfy font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <!-- <link rel="stylesheet" href="css/fontawesome.min.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'styles/style.css'%}">
    <link rel="stylesheet" href="{% static 'styles/aboutstyle.css'%}">


    <!-- swiper cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

    <!-- animation on scroll -->
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

<script>
    setTimeout(function () {
      if ($("#msg").length > 0) {
        $("#msg").remove();
      }
    }, 5000);
</script>

<style>
.rating-wrapper {
  display: inline-block;
}
.rating-wrapper * {
  float: right;
}
/* input {
  display: none;
} */
label {
  font-size: 30px;
}

input:checked ~ label {
  color: red;
}
.alert {
width: 100%;
}
#top-alert {

position: fixed;
margin-top: 100px;
z-index: 99999;
}
#mylink {
text-decoration: none;
}
.alert.alert-server {
margin-bottom: 0;
border-radius: 0;
}
.map-container{
overflow:hidden;
padding-bottom:56.25%;
position:relative;
height:0;
}
.map-container iframe{
left:0;
top:0;
height:100%;
width:100%;
position:absolute;
}




</style>
<title>Sayahat Pakistan</title>

</head>

 <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <a class="navbar-brand" href="{%url 'locapp:dest'%}"><img src="{% static 'images/logo2.png' %}"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>

      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'locapp:dest'%}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{%url 'club:index'%}">Sayahat Adventure clubs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'locapp:aboutUs'%}">About Us</a>
          </li>

            {%if request.user.is_authenticated%}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Post
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="nav-link" href="{%url 'locapp:addRating'%}">Place Rating</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="nav-link" href="{%url 'locapp:addCity'%}">Post a new city</a></li>
              <li><a class="nav-link" href="{%url 'locapp:addPlace'%}">Post a place within city</a></li>
              
              
            </ul>
          </li>
        <li class="nav-item">
        <li class="nav-item" id="show_dp"><a href="/" class="text-danger nav-link example_e" ><span class="nav_link_font">{{user.first_name}}</span></a></li>
          <a class="nav-link image" ><img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="..." height=30px width=30px class="img-fluid rounded-circle"></a>

        </li>
            <li class="nav-item">
            <a class="nav-link" href="{%url 'locapp:logout'%}">Log out</a>
          </li>
            {%else%}
            <li class="nav-item">
            <a class="nav-link text-danger" href="{% provider_login_url "google" %}">Login Via Google</a>
          </li>
            {%endif%}

        </ul>
        <ul class="navbar-nav ms-auto">
          <a href="#footer"><button class="btn">Contact Us</button></a>
        </ul>
      </div>
    </div>
  </nav>
  {% if messages %}
  <div class="alert alert-info alert-server" id="msg" role="alert">
    <div class="text-center">
    <button type="button" class="close" data-dismiss="alert">×</button>
    {% for message in messages %}
        
        {{ message }}
        
        {% endfor %}
      </div>
  </div>
  {% endif %}

  <!-- {% if messages %}
<div id="ms">
    <div id="top-alert" class="alert alert-info" role="alert">
      <div class="text-center">
        <button type="button" class="close" data-dismiss="alert">×</button>
        {% for message in messages %}
        
        {{ message }}
        
        {% endfor %}
      </div>
    </div>
</div>
{% endif %} -->
  

   <body>
        {% block body %}
        {% endblock body %}
{%include 'locapp/newfooter.html'%}

    <script src="{%static 'plugins/parallax-js-master/parallax.min.js'%}"></script>


<!-- Swiper JS -->
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

<!-- <script>
  var mySwiper = new Swiper('#banner .swiper-container',{
    //Original Parameters
    loop:true,
    autoplay:true
  })
</script> -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script>
  var mySwiper = new Swiper('#showcase .swiper-container',{
    //Original Parameters
    loop:true,
    slidesPerView:3,
    spaceBetween:30
  })
</script>
<script>
  AOS.init();
</script>
</body>
</html>

locapp/templates/locapp/directuserrating.html
{% extends 'locapp/base.html' %}
{%load crispy_forms_tags%}
{% block body %}
    <div class="myJumbotron container-fluid d-flex justify-content-center bg-white shadow" data-aos="fade-down-right" style="width: 650px;">
        <form
        method="POST"
        class="col-lg-8 "
        enctype="multipart/form-data"
    >

        <h1 class="d-flex justify-content-center" style="color:#f66342;">Rate a Destination</h1>
        {%csrf_token%}
        <!-- {{form | crispy}} -->
        <div class="mt-5">
            <div class="mb-2">City or Place:</div>

            {{form.place_name}}
        </div>

        <div class="mb-2 mt-5">Rate Destination:</div>
        <div class="text-center">
        <div class="rating-wrapper text-center">
            <input type="radio" id="r1" name="rating" style="display: none;" value="5">
            <label for="r1">&#10038;</label>
            <input type="radio" id="r2" name="rating" style="display: none;" value="4">
            <label for="r2">&#10038;</label>
            <input type="radio" id="r3" name="rating" style="display: none;" value="3">
            <label for="r3">&#10038;</label>
            <input type="radio" id="r4" name="rating" style="display: none;" value="2">
            <label for="r4">&#10038;</label>
            <input type="radio" id="r5" name="rating" style="display: none;" value="1">
            <label for="r5">&#10038;</label>
        </div>
        </div>
        <div class="d-flex justify-content-center">
            <input type="submit" class="hero-btn red-btn mt-3" value="Submit">
        </div>
        <div class="text-center" style="margin-top:40px;">
            If you want to add a new city, <a  href="{% url 'locapp:addCity' %} ">Click Here! </a>
        </div>
        <div class="text-center" style="margin-top:10px;">
            If you want to add a new place, <a  href="{% url 'locapp:addPlace' %} ">Click Here! </a>
        </div>
        </form>

    </div>

{% endblock %}

locapp/templates/locapp/login.html
{% extends 'locapp/base.html' %}

<!-- tags for facebook login  -->
{% load socialaccount %}
{% providers_media_js %}

{% block body %}
    <a class="mt-5 btn btn-lg btn-success" href="{% provider_login_url "google" %}">Login Via Google</a>
    <!-- <a class="btn btn-success" href="{% provider_login_url "facebook" method="oauth2" %}">Login Via Facebook</a> -->
{% endblock %}

locapp/templates/locapp/meta_dest_error_details.html
{% extends 'locapp/base.html' %}
{% block body %}

<div class="myJumbotron container-fluid d-flex justify-content-center bg-white shadow mb-5" data-aos="fade-right" style="width:60%;margin-top: 110px;">
    {% for detail in dest_meta_details %}
    <section class="pt-2">
        <h2 class="heading text-center" style="color:#bcc550"> {{detail.meta_destination_name}} , {{detail.meta_destination}}</h2>
        <h3 class="px-3 heading-orange" style="text-align: left;margin: 1em 0 0.5em 0;
          font-weight: normal;
          font-family: 'Ultra', sans-serif;   
          text-transform: uppercase;
          text-shadow: 0 2px white, 0 3px #777;">About</h3>
        <p class="px-3 py-4 h4" style="text-align:justify"><em>{{detail.meta_destination_desc}}</em>
        </p>
        <h3 class="px-3 py-1 heading-orange" style="text-align: left;margin: 1em 0 0.5em 0;
          font-weight: normal;
          font-family: 'Ultra', sans-serif;   
          text-transform: uppercase;
          text-shadow: 0 2px white, 0 3px #777;">Extra&nbsp;&nbsp;Availables</h3>
        <p class="px-3 py-4 h4" style="text-align:justify"><em>{{detail.destination_extras}}</em>
        </p>
    </section>
    {% endfor %}
</div>
{% endblock %}

locapp/templates/locapp/newfooter.html
{% load static %}
<head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'styles/newstyle.css' %}">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
</head>
<body>
    
  <footer class="footer">
    <div class="footer-container">
        <div class="footer-row">
            <div class="footer-col">
             
                <ul>
                    <li><img src="{% static 'images/logo2.png' %}" style="margin-top: 50px;"></li>
                     
                </ul>
            </div>
            <div class="footer-col">
                <h4>Sayahat Info</h4>
                <ul>
                 
                    <li><a href="{% url 'club:index' %}">Sayahat Adventure Clubs</a></li>
                    <li><a href="{% url 'locapp:Blog' 1 %}">Popular Blogs</a></li>
                    <li><a href="{% url 'locapp:aboutUs' %}">About Us</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Contact & Suggestions</h4>
                <ul>
                    
                    <li><a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=sayahatpk@gmail.com"> sayahatpk@gmail.com</a></li>
                    <li><a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=arfashahji@gmail.com"> arfashahji@gmail.com</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>Follow on Social Media</h4>
                <div class="social-links">
                    <a href="https://www.facebook.com/arfashahji/"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://api.whatsapp.com/send?phone={{+923321516238}}"><i class="fab fa-whatsapp"></i></a>
                    <a href="https://www.instagram.com/syed_arfa459/"><i class="fab fa-instagram"></i></a>
                    <!-- <a href="#"><i class="fab fa-linkedin-in"></i></a> -->
                </div>
            </div>
        </div>
        <!-- <div style="text-align: center; margin-top: 18px;">
        <span style="font-size: 12px;color: #4e4d4d;">&copy; Copyright 2021 Sayahat Official</span>
    </div> -->
    </div>
</footer>
</body>